;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Input.Ability.Slow2",NewTagName="Input.Ability.Slot2")
+GameplayTagRedirects=(OldTagName="Input.Ability.Tag",NewTagName="Input.Ability.Bash")
+GameplayTagList=(Tag="Ability.Type.AreaOfEffect",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Magic",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Melee",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Movement",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Projectile",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Ranged",DevComment="")
+GameplayTagList=(Tag="Class.Mage",DevComment="")
+GameplayTagList=(Tag="Class.Ranger",DevComment="")
+GameplayTagList=(Tag="Class.Warrior",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Bash",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Fireball",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.FrostNova",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Mend",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Mending",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Multishot",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Warcry",DevComment="")
+GameplayTagList=(Tag="Damage.Type.Magic",DevComment="")
+GameplayTagList=(Tag="Damage.Type.Physical",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage.AttackPowerCoefficient",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Base",DevComment="")
+GameplayTagList=(Tag="Data.Damage.DexterityCoefficient",DevComment="")
+GameplayTagList=(Tag="Data.Damage.IntellectCoefficient",DevComment="")
+GameplayTagList=(Tag="Data.Damage.IsMagic",DevComment="")
+GameplayTagList=(Tag="Data.Damage.SpellPowerCoefficient",DevComment="")
+GameplayTagList=(Tag="Data.Damage.StrengthCoefficient",DevComment="")
+GameplayTagList=(Tag="Data.Damage.WeaponCoefficient",DevComment="")
+GameplayTagList=(Tag="Data.ResourceCost",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Bash",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Fireball",DevComment="")
+GameplayTagList=(Tag="Event.Ability.FrostNova",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Mend",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Mending",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Multishot",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Warcry",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Bash",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Fireball",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Mend",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Mending",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Multishot",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Slot1",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Slot2",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Slot3",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Slot4",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Slot5",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Slot6",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="State.Buff.Mending",DevComment="")
+GameplayTagList=(Tag="State.CrowdControl.Frozen",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Frozen",DevComment="")
+GameplayTagList=(Tag="State.HitReaction.Hit",DevComment="")
+GameplayTagList=(Tag="State.Movement.Sprinting",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="")

